### PR TITLE
Fix state ambiguity in Xcode 10

### PR DESCRIPTION
**Pull request by arielpollack**
Not a big deal, old ver didn't compile on Xcode 10.

@pdil

### CODE REVIEW

**Comment by pdil** [comment]
This is causing an error when building because `state` is a get-only property.

https://travis-ci.org/pdil/PDColorPicker/builds/431598740#L836

```
/Users/travis/build/pdil/PDColorPicker/PDColorPicker/Classes/PDPanGestureRecognizer.swift:31:21: error: cannot assign to property: 'state' is a get-only property
        super.state = newValue
        ~~~~~~~~~~~ ^
```

**Comment by arielpollack** [comment]
@pdil you should set travis configuration to use Xcode 10 for building from this point on.

**Comment by pdil** [comment]
@arielpollack Good catch, can you change the following lines in [.travis.yml](https://github.com/pdil/PDColorPicker/blob/master/.travis.yml):

*  `osx_image: xcode9.3` to `osx_image: xcode10`
* `- ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-8, 11.3"` to `- ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-8, 12.0"`

I can merge your changes after those are changed, just to keep it consistent with this pull request to update to Xcode 10 support.

**Comment by arielpollack** [comment]
Sorry for being not responsive about it, and thanks for merging :)

**Pull request merged**
